//Generated by generate_tables
package consts

type Equip struct {
	Equips  string `db:"equips"`
	Uuid    string `db:"uuid"`
	UserId  string `db:"user_id"`
	Level   int    `db:"level"`
	ConfId  int    `db:"conf_id"`
	Evolves string `db:"evolves"`
	Exp     int    `db:"exp"`
}
type User struct {
	Id     int    `db:"id"`
	Users  string `db:"users"`
	Uuid   string `db:"uuid"`
	Level  int    `db:"level"`
	Exp    int    `db:"exp"`
	Name   string `db:"name"`
	Online bool   `db:"online"`
}

var StructToTableNameMap = map[string]string{
	"Equip": "equips",
	"User":  "users",
}
