#!/usr/bin/env ruby

require "./cmds_lib/const.rb"
require "./cmds_lib/cmds.rb"

# Build and save docker images
AppNames.each do |app_name, image_name|
  # Dockerfile path
  docker_filename = "./Dockerfile.#{app_name}.tmp"

  # Gen dockerfile
  Cmds.gen_dockerfile docker_filename, app_name

  # Build docker image
  Cmds.build_image image_name, docker_filename

  # Export docker image
  Cmds.export_image image_name

  # Remove tmp docker file
  `rm #{docker_filename}`
end
