#!/usr/bin/env ruby

require "./cmds_lib/const.rb"
require "./cmds_lib/cmds.rb"

AppNames.each do |name, image_name|
  puts "Load image: #{name} -> #{image_name}.tar"
  Cmds.load_image image_name
end
