#!/usr/bin/env ruby

require "./cmds_lib/const.rb"
require "./cmds_lib/cmds.rb"

AppMappings.each do |image_name, port_mapping|
  puts "Run docker: #{image_name} -> #{port_mapping}"
  Cmds.run_app image_name, port_mapping
end
