apiVersion: v1
kind: Service
metadata:
  name: gos-game-service
  labels:
    app: gos-game-service
spec:
  ports:
  - port: 50053
    name: tcp
  clusterIP: None
  selector:
    app: gos-game-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gos-game-app
spec:
  podManagementPolicy: Parallel
  serviceName: "gos-game-service"
  selector:
    matchLabels:
      app: gos-game-app
  replicas: 3
  template:
    metadata:
      labels:
        app: gos-game-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gos-game-app
        image: savin198/gos-game-app
        imagePullPolicy: Always
        ports:
        - containerPort: 50053
          name: tcp
        volumeMounts:
        - name: tcp
          mountPath: /usr/share/apps/gos-game
  volumeClaimTemplates:
  - metadata:
      name: tcp
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
