apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gos-game-app
  annotations:
    service-per-pod-label: statefulset.kubernetes.io/pod-name
    service-per-pod-ports: "4000:4000"
spec:
  selector:
    matchLabels:
      app: gos-game-app
  serviceName: gos-game-app
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: gos-game-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - gos-game-app
                  - gos-world-app
                  - redis-cluster
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      containers:
      - name: gos-game-app
        image: savin198/gos-game-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: tcp
        - containerPort: 50053
          name: rpc
        volumeMounts:
        - name: tcp
          mountPath: /usr/share/apps/gos-game
        livenessProbe:
          tcpSocket:
            port: 4000
          initialDelaySeconds: 15
          periodSeconds: 20
  volumeClaimTemplates:
  - metadata:
      name: tcp
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
