apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gos-game-app
  annotations:
    service-per-pod-label: statefulset.kubernetes.io/pod-name
    service-per-pod-ports: "4000:4000"
spec:
  selector:
    matchLabels:
      app: gos-game-app
  serviceName: gos-game-app
  podManagementPolicy: Parallel
  replicas: 1
  template:
    metadata:
      labels:
        app: gos-game-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gos-game-app
        image: savin198/gos-game-app
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: tcp
        - containerPort: 50053
          name: rpc
        volumeMounts:
        - name: tcp
          mountPath: /usr/share/apps/gos-game
  volumeClaimTemplates:
  - metadata:
      name: tcp
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
