# GS Messages
GS:
  # Framework Messages
  - protocol:
    id: 1001
    name: SessionAuthParams
    struct:
      AccountId: string
      Token: string

  - protocol:
    id: 1002
    name: SessionAuthResponse
    struct:
      Success: bool

  - protocol:
    id: 1003
    name: Ok
    struct:
      OK: bool

  - protocol:
    id: 1004
    name: Fail
    struct:
      Fail: string

  # Logic Messages
  - protocol:
    id: 2001
    name: EquipLoadParams
    struct:
      PlayerID: string
      EquipId: string
      HeroId: string

  - protocol:
    id: 2002
    name: EquipLoadResponse
    struct:
      PlayerID: string
      EquipId: string
      Level: uint32

  - protocol:
    id: 2003
    name: EquipUnLoadParams
    struct:
      PlayerID: string
      EquipId: string
      HeroId: string

  - protocol:
    id: 2004
    name: EquipUnLoadResponse
    struct:
      PlayerID: string
      EquipId: string
      Level: uint32

  - protocol:
    id: 2005
    name: LoginResponse
    struct:
      Uuid: string
      Level: uint32
      Exp: float32
      Equips: array-EquipLoadResponse
      HeadEquip: EquipLoadParams
      Friends: array-string
      Ages: array-int32

# Room messages
ROOM:
  - protocol:
    id: 3001
    name: RoomJoinParams
    struct:
      RoomId: string
      PlayerId: string

  - protocol:
    id: 3002
    name: RoomJoinResponse
    struct:
      Success: bool

  - protocol:
    id: 3003
    name: RoomJoinNotice
    struct:
      RoomId: string
      NewPlayerId: string
