# GS Messages
GS:
  # ==============Framework Required==============
  SessionAuthParams:
    AccountId: string
    Token: string

  SessionAuthResponse:
    Success: bool

  Ok:
    OK: bool

  Fail:
    Fail: string
  # ==============Framework Required==============

  EquipLoadParams:
    PlayerID: string
    EquipId: string
    HeroId: string

  EquipLoadResponse:
    PlayerID: string
    EquipId: string
    Level: uint32

  EquipUnLoadParams:
    PlayerID: string
    EquipId: string
    HeroId: string

  EquipUnLoadResponse:
    PlayerID: string
    EquipId: string
    Level: uint32

  LoginResponse:
    Uuid: string
    Level: uint32
    Exp: float32
    Equips: array-EquipLoadResponse
    HeadEquip: EquipLoadParams
    Friends: array-string
    Ages: array-int32

# Room messages
ROOM:
  RoomJoinParams:
    RoomId: string
    PlayerId: string
  RoomJoinResponse:
    Success: bool
  RoomJoinNotice:
    RoomId: string
    NewPlayerId: string
