# GS Messages
GS:
  # Framework Messages
  - protocol:
    id: 1001
    name: SessionAuthParams
    struct:
      AccountId: string
      Token: string

  - protocol:
    id: 1002
    name: SessionAuthResponse
    struct:
      Success: bool

  - protocol:
    id: 1003
    name: Ok
    struct:
      OK: bool

  - protocol:
    id: 1004
    name: Fail
    struct:
      Fail: string

  # Logic Messages
  - protocol:
    id: 2001
    name: EquipLoadParams
    struct:
      PlayerID: string
      EquipId: string
      HeroId: string

  - protocol:
    id: 2002
    name: EquipLoadResponse
    struct:
      PlayerID: string
      EquipId: string
      Level: uint32

  - protocol:
    id: 2003
    name: EquipUnLoadParams
    struct:
      PlayerID: string
      EquipId: string
      HeroId: string

  - protocol:
    id: 2004
    name: EquipUnLoadResponse
    struct:
      PlayerID: string
      EquipId: string
      Level: uint32

  - protocol:
    id: 2005
    name: LoginResponse
    struct:
      Uuid: string
      Level: uint32
      Exp: float32
      Equips: array-EquipLoadResponse
      HeadEquip: EquipLoadParams
      Friends: array-string
      Ages: array-int32

  - protocol:
    id: 2006
    name: BuildingCreateParams
    struct:
      Pos: int32
      ConfId: int32
      Instant: bool

  - protocol:
    id: 2007
    name: UpgradeEvent
    struct:
      Uuid: string
      Category: int32
      TargetId: int32
      CreatedAt: int64
      FinishAt: int64
      Duration: int32

  - protocol:
    id: 2008
    name: BuildingUpgradeParams
    struct:
      BuildingId: int32
      Instant: bool

  - protocol:
    id: 2009
    name: BuildingFinishParams
    struct:
      EventId: string
      BuildingId: int32

  - protocol:
    id: 2010
    name: BuildingFinishRsp
    struct:
      EventId: string
      BuildingId: int32
      BuildingLevel: int32

  - protocol:
    id: 2010
    name: BuildingCreateRsp
    struct:
      ResAmounts: array-ResAmount
      Event: UpgradeEvent
      Building: Building

  - protocol:
    id: 2010
    name: BuildingUpgradeRsp
    struct:
      ResAmounts: array-ResAmount
      Event: UpgradeEvent

  - protocol:
    id: 2011
    name: BuildingBuyUpgradeRsp
    struct:
      Gem: int32
      ResAmounts: array-ResAmount
      Building: Building

  - sub_message:
    name: Building
    struct:
      Id: int32
      ConfId: int32
      Pos: int32
      Level: int32

  - sub_message:
    name: ResAmount
    struct:
      Category: int32
      Amount: int64

# Room messages
ROOM:
  - protocol:
    id: 3001
    name: RoomJoinParams
    struct:
      RoomId: string
      PlayerId: string

  - protocol:
    id: 3002
    name: RoomJoinResponse
    struct:
      Success: bool

  - protocol:
    id: 3003
    name: RoomJoinNotice
    struct:
      RoomId: string
      NewPlayerId: string

  - protocol:
    id: 3010
    name: RoomMapMatrixInfos
    struct:
      Points: array-Point

  - sub_message:
    name: Point
    struct:
      X: int32
      Y: int32
