// Generated by tools/gen_routes

package gen_register

import (
	"app/controllers"
	"gen/api/pt"
	"goslib/player"
	"goslib/routes"
)

func RegisterRoutes() {
	equipscontroller := &controllers.EquipsController{}
	routes.Add("EquipLoadParams", func(ctx interface{}, params interface{}) (string, interface{}) {
		return equipscontroller.Load(ctx.(*player.Player), params.(*pt.EquipLoadParams))
	})

	routes.Add("EquipUnLoadParams", func(ctx interface{}, params interface{}) (string, interface{}) {
		return equipscontroller.UnLoad(ctx.(*player.Player), params.(*pt.EquipUnLoadParams))
	})
	roomscontroller := &controllers.RoomsController{}
	routes.Add("RoomJoinParams", func(ctx interface{}, params interface{}) (string, interface{}) {
		return roomscontroller.Join(ctx.(*player.Player), params.(*pt.RoomJoinParams))
	})

}
