// Generated by tools/gen_routes

package gen_register

import (
	"github.com/mafei198/gos/game/app/controllers"
	"github.com/mafei198/gos/goslib/gen/api/pt"
	"github.com/mafei198/gos/goslib/player"
	"github.com/mafei198/gos/goslib/routes"
)

func RegisterRoutes() {
	loginscontroller := &controllers.LoginsController{}
	routes.Add("HeartbeatParams", func(ctx interface{}, params interface{}) interface{} {
		return loginscontroller.Heartbeat(ctx.(*player.Player), params.(*pt.HeartbeatParams))
	})

	equipscontroller := &controllers.EquipsController{}
	routes.Add("EquipLoadParams", func(ctx interface{}, params interface{}) interface{} {
		return equipscontroller.Load(ctx.(*player.Player), params.(*pt.EquipLoadParams))
	})

	routes.Add("EquipUnLoadParams", func(ctx interface{}, params interface{}) interface{} {
		return equipscontroller.UnLoad(ctx.(*player.Player), params.(*pt.EquipUnLoadParams))
	})

	roomscontroller := &controllers.RoomsController{}
	routes.Add("RoomJoinParams", func(ctx interface{}, params interface{}) interface{} {
		return roomscontroller.Join(ctx.(*player.Player), params.(*pt.RoomJoinParams))
	})

	maprpchandler := &controllers.MapRpcHandler{}
	routes.Add("MapRpcInfosParams", func(ctx interface{}, params interface{}) interface{} {
		return maprpchandler.RpcInfo(ctx.(*player.Player), params.(*pt.MapRpcInfosParams))
	})

}
