// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectToGame.proto

package gos_rpc_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RouteMsg struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RouteMsg) Reset()                    { *m = RouteMsg{} }
func (m *RouteMsg) String() string            { return proto.CompactTextString(m) }
func (*RouteMsg) ProtoMessage()               {}
func (*RouteMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RouteMsg) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *RouteMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterMsg struct {
	AccountId    string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	ConnectAppId string `protobuf:"bytes,2,opt,name=connectAppId" json:"connectAppId,omitempty"`
	IsRegister   bool   `protobuf:"varint,3,opt,name=isRegister" json:"isRegister,omitempty"`
}

func (m *RegisterMsg) Reset()                    { *m = RegisterMsg{} }
func (m *RegisterMsg) String() string            { return proto.CompactTextString(m) }
func (*RegisterMsg) ProtoMessage()               {}
func (*RegisterMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RegisterMsg) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *RegisterMsg) GetConnectAppId() string {
	if m != nil {
		return m.ConnectAppId
	}
	return ""
}

func (m *RegisterMsg) GetIsRegister() bool {
	if m != nil {
		return m.IsRegister
	}
	return false
}

type RegisterReply struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *RegisterReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type DeploySceneRequest struct {
	SceneId string `protobuf:"bytes,1,opt,name=sceneId" json:"sceneId,omitempty"`
}

func (m *DeploySceneRequest) Reset()                    { *m = DeploySceneRequest{} }
func (m *DeploySceneRequest) String() string            { return proto.CompactTextString(m) }
func (*DeploySceneRequest) ProtoMessage()               {}
func (*DeploySceneRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *DeploySceneRequest) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

type DeploySceneReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeploySceneReply) Reset()                    { *m = DeploySceneReply{} }
func (m *DeploySceneReply) String() string            { return proto.CompactTextString(m) }
func (*DeploySceneReply) ProtoMessage()               {}
func (*DeploySceneReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *DeploySceneReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*RouteMsg)(nil), "connectApp.RouteMsg")
	proto.RegisterType((*RegisterMsg)(nil), "connectApp.RegisterMsg")
	proto.RegisterType((*RegisterReply)(nil), "connectApp.RegisterReply")
	proto.RegisterType((*DeploySceneRequest)(nil), "connectApp.DeploySceneRequest")
	proto.RegisterType((*DeploySceneReply)(nil), "connectApp.DeploySceneReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RouteConnectGame service

type RouteConnectGameClient interface {
	// A Bidirectional streaming RPC.
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (RouteConnectGame_AgentStreamClient, error)
	DeployScene(ctx context.Context, in *DeploySceneRequest, opts ...grpc.CallOption) (*DeploySceneReply, error)
}

type routeConnectGameClient struct {
	cc *grpc.ClientConn
}

func NewRouteConnectGameClient(cc *grpc.ClientConn) RouteConnectGameClient {
	return &routeConnectGameClient{cc}
}

func (c *routeConnectGameClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (RouteConnectGame_AgentStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RouteConnectGame_serviceDesc.Streams[0], c.cc, "/connectApp.RouteConnectGame/AgentStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeConnectGameAgentStreamClient{stream}
	return x, nil
}

type RouteConnectGame_AgentStreamClient interface {
	Send(*RouteMsg) error
	Recv() (*RouteMsg, error)
	grpc.ClientStream
}

type routeConnectGameAgentStreamClient struct {
	grpc.ClientStream
}

func (x *routeConnectGameAgentStreamClient) Send(m *RouteMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeConnectGameAgentStreamClient) Recv() (*RouteMsg, error) {
	m := new(RouteMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeConnectGameClient) DeployScene(ctx context.Context, in *DeploySceneRequest, opts ...grpc.CallOption) (*DeploySceneReply, error) {
	out := new(DeploySceneReply)
	err := grpc.Invoke(ctx, "/connectApp.RouteConnectGame/DeployScene", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RouteConnectGame service

type RouteConnectGameServer interface {
	// A Bidirectional streaming RPC.
	AgentStream(RouteConnectGame_AgentStreamServer) error
	DeployScene(context.Context, *DeploySceneRequest) (*DeploySceneReply, error)
}

func RegisterRouteConnectGameServer(s *grpc.Server, srv RouteConnectGameServer) {
	s.RegisterService(&_RouteConnectGame_serviceDesc, srv)
}

func _RouteConnectGame_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteConnectGameServer).AgentStream(&routeConnectGameAgentStreamServer{stream})
}

type RouteConnectGame_AgentStreamServer interface {
	Send(*RouteMsg) error
	Recv() (*RouteMsg, error)
	grpc.ServerStream
}

type routeConnectGameAgentStreamServer struct {
	grpc.ServerStream
}

func (x *routeConnectGameAgentStreamServer) Send(m *RouteMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeConnectGameAgentStreamServer) Recv() (*RouteMsg, error) {
	m := new(RouteMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteConnectGame_DeployScene_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploySceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConnectGameServer).DeployScene(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.RouteConnectGame/DeployScene",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConnectGameServer).DeployScene(ctx, req.(*DeploySceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteConnectGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.RouteConnectGame",
	HandlerType: (*RouteConnectGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployScene",
			Handler:    _RouteConnectGame_DeployScene_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _RouteConnectGame_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connectToGame.proto",
}

func init() { proto.RegisterFile("connectToGame.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xed, 0x7e, 0x9f, 0xd4, 0x76, 0xda, 0x62, 0x19, 0x45, 0x42, 0x29, 0xa5, 0xec, 0xc5, 0x1c,
	0x24, 0x88, 0x5e, 0x05, 0xa9, 0x0a, 0xd2, 0x43, 0x2f, 0x5b, 0x4f, 0x5e, 0xca, 0xba, 0x1d, 0x42,
	0xa1, 0xcd, 0xae, 0xd9, 0xcd, 0x21, 0x7f, 0xc7, 0x5f, 0x2a, 0x59, 0xbb, 0x26, 0x45, 0xc5, 0x53,
	0xe6, 0xbd, 0x3c, 0xde, 0xbc, 0x79, 0x0b, 0xa7, 0x4a, 0x67, 0x19, 0x29, 0xf7, 0xac, 0x9f, 0xe4,
	0x8e, 0x12, 0x93, 0x6b, 0xa7, 0x11, 0xf6, 0xe4, 0xcc, 0x18, 0x7e, 0x0b, 0x1d, 0xa1, 0x0b, 0x47,
	0x0b, 0x9b, 0xe2, 0x18, 0xba, 0x52, 0x29, 0x5d, 0x64, 0x6e, 0xbe, 0x8e, 0xd8, 0x94, 0xc5, 0x5d,
	0x51, 0x13, 0x88, 0x70, 0xb4, 0x96, 0x4e, 0x46, 0xff, 0xa6, 0x2c, 0xee, 0x0b, 0x3f, 0x73, 0x0d,
	0x3d, 0x41, 0xe9, 0xc6, 0x3a, 0xca, 0xff, 0x36, 0xe0, 0xd0, 0xaf, 0x17, 0xcf, 0xd7, 0xde, 0xa8,
	0x2b, 0x0e, 0x38, 0x9c, 0x00, 0x6c, 0x6c, 0xb0, 0x8c, 0xfe, 0x4f, 0x59, 0xdc, 0x11, 0x0d, 0x86,
	0x5f, 0xc0, 0x20, 0xcc, 0x82, 0xcc, 0xb6, 0xc4, 0x73, 0x68, 0x5b, 0x27, 0x5d, 0x61, 0xfd, 0xbe,
	0x8e, 0xd8, 0x23, 0x9e, 0x00, 0x3e, 0x92, 0xd9, 0xea, 0x72, 0xa9, 0x28, 0x23, 0x41, 0x6f, 0x05,
	0x59, 0x87, 0x11, 0x1c, 0xdb, 0x0a, 0x7f, 0xc5, 0x0b, 0x90, 0x5f, 0xc2, 0xf0, 0x40, 0x5f, 0x79,
	0x57, 0xea, 0x42, 0x29, 0xb2, 0xc1, 0x3c, 0xc0, 0xeb, 0x77, 0x06, 0x43, 0x5f, 0xdb, 0xc3, 0x67,
	0xf8, 0xaa, 0x5c, 0xbc, 0x83, 0xde, 0x2c, 0xa5, 0xcc, 0x2d, 0x5d, 0x4e, 0x72, 0x87, 0x67, 0x49,
	0x7d, 0x59, 0x12, 0x3a, 0x1e, 0xfd, 0xc8, 0xf2, 0x56, 0xcc, 0xae, 0x18, 0x2e, 0xa0, 0xd7, 0xc8,
	0x80, 0x93, 0xa6, 0xf4, 0xfb, 0x31, 0xa3, 0xf1, 0xaf, 0xff, 0xcd, 0xb6, 0xe4, 0xad, 0xfb, 0x93,
	0x97, 0x41, 0xaa, 0xed, 0x2a, 0x37, 0x6a, 0xe5, 0xdf, 0xfd, 0xb5, 0xed, 0x3f, 0x37, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xc7, 0x9e, 0x1d, 0xf5, 0x15, 0x02, 0x00, 0x00,
}
