// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectApp.proto

/*
Package gos_rpc_proto is a generated protocol buffer package.

It is generated from these files:
	connectApp.proto
	connectToGame.proto
	gameApp.proto

It has these top-level messages:
	DispatchRequest
	DispatchReply
	AgentInfo
	OkReply
	RouteMsg
	RegisterMsg
	RegisterReply
	DeploySceneRequest
	DeploySceneReply
	RequestPlayerRequest
	RequestPlayerReply
	DispatchGameRequest
	DispatchGameReply
	ReportGameRequest
	ReportGameReply
*/
package gos_rpc_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DispatchRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	GroupId   string `protobuf:"bytes,2,opt,name=groupId" json:"groupId,omitempty"`
}

func (m *DispatchRequest) Reset()                    { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()               {}
func (*DispatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DispatchRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type DispatchReply struct {
	ConnectAppId   string `protobuf:"bytes,1,opt,name=connectAppId" json:"connectAppId,omitempty"`
	ConnectAppHost string `protobuf:"bytes,2,opt,name=connectAppHost" json:"connectAppHost,omitempty"`
	ConnectAppPort string `protobuf:"bytes,3,opt,name=connectAppPort" json:"connectAppPort,omitempty"`
}

func (m *DispatchReply) Reset()                    { *m = DispatchReply{} }
func (m *DispatchReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchReply) ProtoMessage()               {}
func (*DispatchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DispatchReply) GetConnectAppId() string {
	if m != nil {
		return m.ConnectAppId
	}
	return ""
}

func (m *DispatchReply) GetConnectAppHost() string {
	if m != nil {
		return m.ConnectAppHost
	}
	return ""
}

func (m *DispatchReply) GetConnectAppPort() string {
	if m != nil {
		return m.ConnectAppPort
	}
	return ""
}

type AgentInfo struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Ccu  int32  `protobuf:"varint,4,opt,name=ccu" json:"ccu,omitempty"`
}

func (m *AgentInfo) Reset()                    { *m = AgentInfo{} }
func (m *AgentInfo) String() string            { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()               {}
func (*AgentInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AgentInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *AgentInfo) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AgentInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *AgentInfo) GetCcu() int32 {
	if m != nil {
		return m.Ccu
	}
	return 0
}

type OkReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *OkReply) Reset()                    { *m = OkReply{} }
func (m *OkReply) String() string            { return proto.CompactTextString(m) }
func (*OkReply) ProtoMessage()               {}
func (*OkReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *OkReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*DispatchRequest)(nil), "connectApp.DispatchRequest")
	proto.RegisterType((*DispatchReply)(nil), "connectApp.DispatchReply")
	proto.RegisterType((*AgentInfo)(nil), "connectApp.AgentInfo")
	proto.RegisterType((*OkReply)(nil), "connectApp.OkReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dispatcher service

type DispatcherClient interface {
	DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error)
	ReportAgentInfo(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*OkReply, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error) {
	out := new(DispatchReply)
	err := grpc.Invoke(ctx, "/connectApp.Dispatcher/DispatchPlayer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dispatcherClient) ReportAgentInfo(ctx context.Context, in *AgentInfo, opts ...grpc.CallOption) (*OkReply, error) {
	out := new(OkReply)
	err := grpc.Invoke(ctx, "/connectApp.Dispatcher/ReportAgentInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dispatcher service

type DispatcherServer interface {
	DispatchPlayer(context.Context, *DispatchRequest) (*DispatchReply, error)
	ReportAgentInfo(context.Context, *AgentInfo) (*OkReply, error)
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_DispatchPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).DispatchPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.Dispatcher/DispatchPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).DispatchPlayer(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dispatcher_ReportAgentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).ReportAgentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.Dispatcher/ReportAgentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).ReportAgentInfo(ctx, req.(*AgentInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchPlayer",
			Handler:    _Dispatcher_DispatchPlayer_Handler,
		},
		{
			MethodName: "ReportAgentInfo",
			Handler:    _Dispatcher_ReportAgentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectApp.proto",
}

func init() { proto.RegisterFile("connectApp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0xc6, 0x9b, 0xb7, 0x7d, 0x09, 0x39, 0xd1, 0xa6, 0x3a, 0x84, 0x64, 0x0a, 0x43, 0x65, 0x24,
	0xd4, 0xa9, 0x03, 0x7c, 0x00, 0x54, 0xc4, 0x40, 0x58, 0xa8, 0xb2, 0xc1, 0x52, 0x05, 0xd7, 0xa4,
	0x15, 0x51, 0x6c, 0xfc, 0x67, 0xc8, 0xcc, 0xa7, 0xe0, 0xdb, 0xa2, 0x98, 0xa6, 0x4e, 0x23, 0xa6,
	0x3c, 0xcf, 0xcf, 0xa7, 0xe7, 0x7c, 0x17, 0xc3, 0x98, 0x89, 0xb2, 0xe4, 0xcc, 0x2c, 0xa4, 0x9c,
	0x4b, 0x25, 0x8c, 0x40, 0xf0, 0x84, 0x26, 0x10, 0x3f, 0x6c, 0xb5, 0xcc, 0x0c, 0xdb, 0xa4, 0xfc,
	0xd3, 0x72, 0x6d, 0xf0, 0x12, 0xa2, 0x8c, 0x31, 0x61, 0x4b, 0x93, 0xac, 0x49, 0x30, 0x0d, 0x66,
	0x51, 0xea, 0x01, 0x12, 0x08, 0x73, 0x25, 0xac, 0x4c, 0xd6, 0xe4, 0x9f, 0x3b, 0x6b, 0x2c, 0xfd,
	0x0a, 0x60, 0xe8, 0xb3, 0x64, 0x51, 0x21, 0x85, 0x13, 0xdf, 0x6a, 0x1f, 0x76, 0xc0, 0xf0, 0x1a,
	0x46, 0xde, 0x3f, 0x0a, 0x6d, 0x76, 0xb1, 0x1d, 0x7a, 0x58, 0xb7, 0x14, 0xca, 0x90, 0x7e, 0xb7,
	0xae, 0xa6, 0xf4, 0x05, 0xa2, 0x45, 0xce, 0x4b, 0x93, 0x94, 0xef, 0x02, 0x11, 0x06, 0xd6, 0x6e,
	0x9b, 0xc6, 0x4e, 0xd7, 0x6c, 0xe3, 0xdb, 0x38, 0x5d, 0x33, 0xe9, 0x23, 0x9d, 0xc6, 0x31, 0xf4,
	0x19, 0xb3, 0x64, 0x30, 0x0d, 0x66, 0xff, 0xd3, 0x5a, 0xd2, 0x2b, 0x08, 0x9f, 0x3f, 0x7e, 0x27,
	0x23, 0x10, 0x6a, 0xcb, 0x18, 0xd7, 0xda, 0x65, 0x1f, 0xa7, 0x8d, 0xbd, 0xf9, 0x0e, 0x00, 0x9a,
	0x2d, 0x70, 0x85, 0x4f, 0x30, 0x6a, 0xdc, 0xb2, 0xc8, 0x2a, 0xae, 0xf0, 0x62, 0xde, 0xfa, 0x21,
	0x9d, 0xdd, 0x4f, 0xce, 0xff, 0x3e, 0x94, 0x45, 0x45, 0x7b, 0x78, 0x07, 0x71, 0xca, 0xeb, 0xbb,
	0xf9, 0x01, 0xcf, 0xda, 0xf5, 0x7b, 0x3c, 0x39, 0x6d, 0xe3, 0xdd, 0x9d, 0x69, 0xef, 0x3e, 0x7e,
	0x1d, 0xe6, 0x42, 0xaf, 0x94, 0x64, 0x2b, 0xf7, 0x12, 0xde, 0x8e, 0xdc, 0xe7, 0xf6, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x90, 0x9d, 0xa2, 0x11, 0x24, 0x02, 0x00, 0x00,
}
