// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameApp.proto

package gos_rpc_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DispatchGameRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	ServerId  string `protobuf:"bytes,2,opt,name=serverId" json:"serverId,omitempty"`
	SceneId   string `protobuf:"bytes,3,opt,name=sceneId" json:"sceneId,omitempty"`
}

func (m *DispatchGameRequest) Reset()                    { *m = DispatchGameRequest{} }
func (m *DispatchGameRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchGameRequest) ProtoMessage()               {}
func (*DispatchGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *DispatchGameRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DispatchGameRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *DispatchGameRequest) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

type DispatchGameReply struct {
	GameAppId   string `protobuf:"bytes,1,opt,name=gameAppId" json:"gameAppId,omitempty"`
	GameAppHost string `protobuf:"bytes,2,opt,name=gameAppHost" json:"gameAppHost,omitempty"`
	GameAppPort string `protobuf:"bytes,3,opt,name=gameAppPort" json:"gameAppPort,omitempty"`
	SceneId     string `protobuf:"bytes,4,opt,name=sceneId" json:"sceneId,omitempty"`
}

func (m *DispatchGameReply) Reset()                    { *m = DispatchGameReply{} }
func (m *DispatchGameReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchGameReply) ProtoMessage()               {}
func (*DispatchGameReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DispatchGameReply) GetGameAppId() string {
	if m != nil {
		return m.GameAppId
	}
	return ""
}

func (m *DispatchGameReply) GetGameAppHost() string {
	if m != nil {
		return m.GameAppHost
	}
	return ""
}

func (m *DispatchGameReply) GetGameAppPort() string {
	if m != nil {
		return m.GameAppPort
	}
	return ""
}

func (m *DispatchGameReply) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

type ReportGameRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Ccu  int32  `protobuf:"varint,4,opt,name=ccu" json:"ccu,omitempty"`
}

func (m *ReportGameRequest) Reset()                    { *m = ReportGameRequest{} }
func (m *ReportGameRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportGameRequest) ProtoMessage()               {}
func (*ReportGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ReportGameRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ReportGameRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ReportGameRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *ReportGameRequest) GetCcu() int32 {
	if m != nil {
		return m.Ccu
	}
	return 0
}

type ReportGameReply struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *ReportGameReply) Reset()                    { *m = ReportGameReply{} }
func (m *ReportGameReply) String() string            { return proto.CompactTextString(m) }
func (*ReportGameReply) ProtoMessage()               {}
func (*ReportGameReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ReportGameReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*DispatchGameRequest)(nil), "connectApp.DispatchGameRequest")
	proto.RegisterType((*DispatchGameReply)(nil), "connectApp.DispatchGameReply")
	proto.RegisterType((*ReportGameRequest)(nil), "connectApp.ReportGameRequest")
	proto.RegisterType((*ReportGameReply)(nil), "connectApp.ReportGameReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameDispatcher service

type GameDispatcherClient interface {
	DispatchGame(ctx context.Context, in *DispatchGameRequest, opts ...grpc.CallOption) (*DispatchGameReply, error)
	ReportGameInfo(ctx context.Context, in *ReportGameRequest, opts ...grpc.CallOption) (*ReportGameReply, error)
}

type gameDispatcherClient struct {
	cc *grpc.ClientConn
}

func NewGameDispatcherClient(cc *grpc.ClientConn) GameDispatcherClient {
	return &gameDispatcherClient{cc}
}

func (c *gameDispatcherClient) DispatchGame(ctx context.Context, in *DispatchGameRequest, opts ...grpc.CallOption) (*DispatchGameReply, error) {
	out := new(DispatchGameReply)
	err := grpc.Invoke(ctx, "/connectApp.GameDispatcher/DispatchGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameDispatcherClient) ReportGameInfo(ctx context.Context, in *ReportGameRequest, opts ...grpc.CallOption) (*ReportGameReply, error) {
	out := new(ReportGameReply)
	err := grpc.Invoke(ctx, "/connectApp.GameDispatcher/ReportGameInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameDispatcher service

type GameDispatcherServer interface {
	DispatchGame(context.Context, *DispatchGameRequest) (*DispatchGameReply, error)
	ReportGameInfo(context.Context, *ReportGameRequest) (*ReportGameReply, error)
}

func RegisterGameDispatcherServer(s *grpc.Server, srv GameDispatcherServer) {
	s.RegisterService(&_GameDispatcher_serviceDesc, srv)
}

func _GameDispatcher_DispatchGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDispatcherServer).DispatchGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.GameDispatcher/DispatchGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDispatcherServer).DispatchGame(ctx, req.(*DispatchGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameDispatcher_ReportGameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDispatcherServer).ReportGameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.GameDispatcher/ReportGameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDispatcherServer).ReportGameInfo(ctx, req.(*ReportGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameDispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.GameDispatcher",
	HandlerType: (*GameDispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchGame",
			Handler:    _GameDispatcher_DispatchGame_Handler,
		},
		{
			MethodName: "ReportGameInfo",
			Handler:    _GameDispatcher_ReportGameInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameApp.proto",
}

func init() { proto.RegisterFile("gameApp.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0xad, 0xa0, 0xc2, 0x28, 0x20, 0xeb, 0xa5, 0x41, 0x8d, 0xa4, 0x27, 0x13, 0x13, 0x0e,
	0xfa, 0x04, 0x18, 0x13, 0xed, 0xc5, 0x90, 0x1e, 0xbd, 0x90, 0xba, 0x8c, 0xd0, 0x04, 0xba, 0xe3,
	0xfe, 0x31, 0xe1, 0x29, 0x7c, 0x17, 0x9f, 0xd0, 0xec, 0xa6, 0x65, 0xb7, 0x51, 0x4e, 0x9d, 0xef,
	0x9b, 0x69, 0x7f, 0xdf, 0xce, 0x16, 0x7a, 0xcb, 0x7c, 0x83, 0x53, 0xa2, 0x09, 0x49, 0xa1, 0x05,
	0x03, 0x2e, 0xca, 0x12, 0xb9, 0x9e, 0x12, 0x25, 0x05, 0x5c, 0x3c, 0x15, 0x8a, 0x72, 0xcd, 0x57,
	0xcf, 0xf9, 0x06, 0x33, 0xfc, 0x34, 0xa8, 0x34, 0xbb, 0x82, 0x6e, 0xce, 0xb9, 0x30, 0xa5, 0x4e,
	0x17, 0x71, 0x34, 0x8e, 0x6e, 0xbb, 0x99, 0x37, 0xd8, 0x08, 0x3a, 0x0a, 0xe5, 0x17, 0xca, 0x74,
	0x11, 0x1f, 0xba, 0xe6, 0x4e, 0xb3, 0x18, 0x4e, 0x14, 0xc7, 0x12, 0xd3, 0x45, 0xdc, 0x72, 0xad,
	0x5a, 0x26, 0xdf, 0x11, 0x0c, 0x9b, 0x2c, 0x5a, 0x6f, 0x2d, 0xa9, 0x4a, 0xe7, 0x49, 0x3b, 0x83,
	0x8d, 0xe1, 0xb4, 0x12, 0x2f, 0x42, 0xe9, 0x0a, 0x16, 0x5a, 0xc1, 0xc4, 0x4c, 0x48, 0x5d, 0x31,
	0x43, 0x2b, 0x4c, 0xd4, 0x6e, 0x26, 0xca, 0x61, 0x98, 0x21, 0x09, 0xa9, 0xc3, 0xa3, 0x33, 0x68,
	0x1b, 0x53, 0xd4, 0x59, 0x5c, 0x6d, 0xbd, 0x95, 0xe7, 0xbb, 0xda, 0x7a, 0xe4, 0x89, 0xae, 0x66,
	0xe7, 0xd0, 0xe2, 0xdc, 0x38, 0xcc, 0x51, 0x66, 0xcb, 0xe4, 0x0e, 0x06, 0x21, 0xc2, 0x9e, 0xd8,
	0xe6, 0x31, 0x9c, 0xa3, 0x52, 0x8e, 0xd1, 0xc9, 0x6a, 0x79, 0xff, 0x13, 0x41, 0xdf, 0xce, 0xd5,
	0x5b, 0x42, 0xc9, 0x66, 0x70, 0x16, 0xee, 0x8c, 0xdd, 0x4c, 0xfc, 0xe5, 0x4d, 0xfe, 0xb9, 0xb9,
	0xd1, 0xf5, 0xfe, 0x01, 0x5a, 0x6f, 0x93, 0x03, 0xf6, 0x0a, 0x7d, 0x9f, 0x28, 0x2d, 0x3f, 0x04,
	0x6b, 0xbc, 0xf2, 0x67, 0x21, 0xa3, 0xcb, 0x7d, 0x6d, 0xf7, 0xbd, 0xc7, 0xc1, 0x5b, 0x6f, 0x29,
	0xd4, 0x5c, 0x12, 0x9f, 0xbb, 0xdf, 0xeb, 0xfd, 0xd8, 0x3d, 0x1e, 0x7e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x5c, 0xac, 0xe9, 0x76, 0x02, 0x00, 0x00,
}
