// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectApp.proto

/*
Package connectAppProto is a generated protocol buffer package.

It is generated from these files:
	connectApp.proto

It has these top-level messages:
	DispatchRequest
	DispatchReply
*/
package connectAppProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DispatchRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *DispatchRequest) Reset()                    { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()               {}
func (*DispatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

type DispatchReply struct {
	ConnectAppHost string `protobuf:"bytes,1,opt,name=connectAppHost" json:"connectAppHost,omitempty"`
	ConnectAppPort string `protobuf:"bytes,2,opt,name=connectAppPort" json:"connectAppPort,omitempty"`
}

func (m *DispatchReply) Reset()                    { *m = DispatchReply{} }
func (m *DispatchReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchReply) ProtoMessage()               {}
func (*DispatchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DispatchReply) GetConnectAppHost() string {
	if m != nil {
		return m.ConnectAppHost
	}
	return ""
}

func (m *DispatchReply) GetConnectAppPort() string {
	if m != nil {
		return m.ConnectAppPort
	}
	return ""
}

func init() {
	proto.RegisterType((*DispatchRequest)(nil), "connectApp.DispatchRequest")
	proto.RegisterType((*DispatchReply)(nil), "connectApp.DispatchReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dispatcher service

type DispatcherClient interface {
	DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error) {
	out := new(DispatchReply)
	err := grpc.Invoke(ctx, "/connectApp.Dispatcher/DispatchPlayer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dispatcher service

type DispatcherServer interface {
	DispatchPlayer(context.Context, *DispatchRequest) (*DispatchReply, error)
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_DispatchPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).DispatchPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.Dispatcher/DispatchPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).DispatchPlayer(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchPlayer",
			Handler:    _Dispatcher_DispatchPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectApp.proto",
}

func init() { proto.RegisterFile("connectApp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0x71, 0x2c, 0x28, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xe9, 0x73, 0xf1, 0xbb, 0x64, 0x16, 0x17, 0x24, 0x96, 0x24, 0x67, 0x04, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x26, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x78, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x94, 0xe2, 0xb9, 0x78, 0x11, 0x1a, 0x0a,
	0x72, 0x2a, 0x85, 0xd4, 0xb8, 0xf8, 0x10, 0xe6, 0x79, 0xe4, 0x17, 0x97, 0x40, 0xf5, 0xa0, 0x89,
	0xa2, 0xaa, 0x0b, 0xc8, 0x2f, 0x2a, 0x91, 0x60, 0x42, 0x57, 0x07, 0x12, 0x35, 0x8a, 0xe0, 0xe2,
	0x82, 0x59, 0x90, 0x5a, 0x24, 0xe4, 0xc5, 0xc5, 0x07, 0xe3, 0x05, 0xe4, 0x24, 0x56, 0xa6, 0x16,
	0x09, 0x49, 0xeb, 0x21, 0x79, 0x08, 0xcd, 0xed, 0x52, 0x92, 0xd8, 0x25, 0x0b, 0x72, 0x2a, 0x95,
	0x18, 0x9c, 0x04, 0xa3, 0xf8, 0x91, 0xec, 0x02, 0x05, 0x45, 0x12, 0x1b, 0x38, 0x44, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x39, 0x19, 0x69, 0xac, 0x25, 0x01, 0x00, 0x00,
}
