// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gameApp.proto

package connectAppProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DispatchGameRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	ServerId  string `protobuf:"bytes,2,opt,name=serverId" json:"serverId,omitempty"`
	SceneId   string `protobuf:"bytes,3,opt,name=sceneId" json:"sceneId,omitempty"`
}

func (m *DispatchGameRequest) Reset()                    { *m = DispatchGameRequest{} }
func (m *DispatchGameRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchGameRequest) ProtoMessage()               {}
func (*DispatchGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *DispatchGameRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DispatchGameRequest) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *DispatchGameRequest) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

type DispatchGameReply struct {
	GameAppId   string `protobuf:"bytes,1,opt,name=gameAppId" json:"gameAppId,omitempty"`
	GameAppHost string `protobuf:"bytes,2,opt,name=gameAppHost" json:"gameAppHost,omitempty"`
	GameAppPort string `protobuf:"bytes,3,opt,name=gameAppPort" json:"gameAppPort,omitempty"`
}

func (m *DispatchGameReply) Reset()                    { *m = DispatchGameReply{} }
func (m *DispatchGameReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchGameReply) ProtoMessage()               {}
func (*DispatchGameReply) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DispatchGameReply) GetGameAppId() string {
	if m != nil {
		return m.GameAppId
	}
	return ""
}

func (m *DispatchGameReply) GetGameAppHost() string {
	if m != nil {
		return m.GameAppHost
	}
	return ""
}

func (m *DispatchGameReply) GetGameAppPort() string {
	if m != nil {
		return m.GameAppPort
	}
	return ""
}

func init() {
	proto.RegisterType((*DispatchGameRequest)(nil), "connectApp.DispatchGameRequest")
	proto.RegisterType((*DispatchGameReply)(nil), "connectApp.DispatchGameReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameDispatcher service

type GameDispatcherClient interface {
	DispatchGame(ctx context.Context, in *DispatchGameRequest, opts ...grpc.CallOption) (*DispatchGameReply, error)
}

type gameDispatcherClient struct {
	cc *grpc.ClientConn
}

func NewGameDispatcherClient(cc *grpc.ClientConn) GameDispatcherClient {
	return &gameDispatcherClient{cc}
}

func (c *gameDispatcherClient) DispatchGame(ctx context.Context, in *DispatchGameRequest, opts ...grpc.CallOption) (*DispatchGameReply, error) {
	out := new(DispatchGameReply)
	err := grpc.Invoke(ctx, "/connectApp.GameDispatcher/DispatchGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GameDispatcher service

type GameDispatcherServer interface {
	DispatchGame(context.Context, *DispatchGameRequest) (*DispatchGameReply, error)
}

func RegisterGameDispatcherServer(s *grpc.Server, srv GameDispatcherServer) {
	s.RegisterService(&_GameDispatcher_serviceDesc, srv)
}

func _GameDispatcher_DispatchGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameDispatcherServer).DispatchGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.GameDispatcher/DispatchGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameDispatcherServer).DispatchGame(ctx, req.(*DispatchGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameDispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.GameDispatcher",
	HandlerType: (*GameDispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchGame",
			Handler:    _GameDispatcher_DispatchGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gameApp.proto",
}

func init() { proto.RegisterFile("gameApp.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x5d, 0x05, 0x75, 0xc7, 0x7f, 0x6c, 0xbc, 0x84, 0x45, 0xb1, 0xf4, 0xe4, 0xa9, 0x07,
	0xfd, 0x04, 0x15, 0x41, 0x7b, 0x2b, 0x3d, 0x7a, 0x4b, 0xd3, 0x41, 0x0b, 0x6d, 0x32, 0x26, 0xa9,
	0xd0, 0x6f, 0x2f, 0x2d, 0x69, 0x13, 0xc1, 0x3d, 0xbe, 0x37, 0x0f, 0x7e, 0xc3, 0x0f, 0xae, 0x3e,
	0x45, 0x8f, 0x39, 0x51, 0x46, 0x46, 0x3b, 0xcd, 0x40, 0x6a, 0xa5, 0x50, 0xba, 0x9c, 0x28, 0x6d,
	0xe1, 0xf6, 0xb5, 0xb5, 0x24, 0x9c, 0xfc, 0x7a, 0x13, 0x3d, 0x56, 0xf8, 0x3d, 0xa0, 0x75, 0xec,
	0x0e, 0xb6, 0x42, 0x4a, 0x3d, 0x28, 0x57, 0x34, 0x7c, 0x93, 0x6c, 0x1e, 0xb7, 0x55, 0x28, 0xd8,
	0x1e, 0xce, 0x2d, 0x9a, 0x1f, 0x34, 0x45, 0xc3, 0x8f, 0xe7, 0xe3, 0x9a, 0x19, 0x87, 0x33, 0x2b,
	0x51, 0x61, 0xd1, 0xf0, 0x93, 0xf9, 0xb4, 0xc4, 0x74, 0x80, 0xdd, 0x5f, 0x14, 0x75, 0xe3, 0x04,
	0xf2, 0xcf, 0x05, 0xd0, 0x5a, 0xb0, 0x04, 0x2e, 0x7c, 0x78, 0xd7, 0xd6, 0x79, 0x56, 0x5c, 0x45,
	0x8b, 0x52, 0x1b, 0xe7, 0x91, 0x71, 0xf5, 0x54, 0xc3, 0xf5, 0x84, 0x5b, 0xd0, 0x68, 0x58, 0x09,
	0x97, 0xf1, 0x23, 0xec, 0x21, 0x0b, 0x42, 0xb2, 0x7f, 0x6c, 0xec, 0xef, 0x0f, 0x0f, 0xa8, 0x1b,
	0xd3, 0xa3, 0x97, 0xdd, 0xc7, 0x4d, 0x58, 0x94, 0x93, 0xe4, 0xfa, 0x74, 0x76, 0xfd, 0xfc, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0x66, 0x2b, 0xdf, 0x7c, 0x01, 0x00, 0x00,
}
