// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectToGame.proto

package gosRPcProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A RouteNote is a message sent while at a given point.
type RouteMsg struct {
	// The location from which the message is sent.
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	// The message to be sent.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RouteMsg) Reset()                    { *m = RouteMsg{} }
func (m *RouteMsg) String() string            { return proto.CompactTextString(m) }
func (*RouteMsg) ProtoMessage()               {}
func (*RouteMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RouteMsg) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *RouteMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterMsg struct {
	AccountId    string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	ConnectAppId string `protobuf:"bytes,2,opt,name=connectAppId" json:"connectAppId,omitempty"`
	IsRegister   bool   `protobuf:"varint,3,opt,name=isRegister" json:"isRegister,omitempty"`
}

func (m *RegisterMsg) Reset()                    { *m = RegisterMsg{} }
func (m *RegisterMsg) String() string            { return proto.CompactTextString(m) }
func (*RegisterMsg) ProtoMessage()               {}
func (*RegisterMsg) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RegisterMsg) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *RegisterMsg) GetConnectAppId() string {
	if m != nil {
		return m.ConnectAppId
	}
	return ""
}

func (m *RegisterMsg) GetIsRegister() bool {
	if m != nil {
		return m.IsRegister
	}
	return false
}

type RegisterReply struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *RegisterReply) Reset()                    { *m = RegisterReply{} }
func (m *RegisterReply) String() string            { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()               {}
func (*RegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *RegisterReply) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*RouteMsg)(nil), "connectApp.RouteMsg")
	proto.RegisterType((*RegisterMsg)(nil), "connectApp.RegisterMsg")
	proto.RegisterType((*RegisterReply)(nil), "connectApp.RegisterReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RouteConnectGame service

type RouteConnectGameClient interface {
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	AgentStream(ctx context.Context, opts ...grpc.CallOption) (RouteConnectGame_AgentStreamClient, error)
	AgentRegister(ctx context.Context, in *RegisterMsg, opts ...grpc.CallOption) (*RegisterReply, error)
}

type routeConnectGameClient struct {
	cc *grpc.ClientConn
}

func NewRouteConnectGameClient(cc *grpc.ClientConn) RouteConnectGameClient {
	return &routeConnectGameClient{cc}
}

func (c *routeConnectGameClient) AgentStream(ctx context.Context, opts ...grpc.CallOption) (RouteConnectGame_AgentStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RouteConnectGame_serviceDesc.Streams[0], c.cc, "/connectApp.RouteConnectGame/AgentStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeConnectGameAgentStreamClient{stream}
	return x, nil
}

type RouteConnectGame_AgentStreamClient interface {
	Send(*RouteMsg) error
	Recv() (*RouteMsg, error)
	grpc.ClientStream
}

type routeConnectGameAgentStreamClient struct {
	grpc.ClientStream
}

func (x *routeConnectGameAgentStreamClient) Send(m *RouteMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeConnectGameAgentStreamClient) Recv() (*RouteMsg, error) {
	m := new(RouteMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeConnectGameClient) AgentRegister(ctx context.Context, in *RegisterMsg, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := grpc.Invoke(ctx, "/connectApp.RouteConnectGame/AgentRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RouteConnectGame service

type RouteConnectGameServer interface {
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	AgentStream(RouteConnectGame_AgentStreamServer) error
	AgentRegister(context.Context, *RegisterMsg) (*RegisterReply, error)
}

func RegisterRouteConnectGameServer(s *grpc.Server, srv RouteConnectGameServer) {
	s.RegisterService(&_RouteConnectGame_serviceDesc, srv)
}

func _RouteConnectGame_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteConnectGameServer).AgentStream(&routeConnectGameAgentStreamServer{stream})
}

type RouteConnectGame_AgentStreamServer interface {
	Send(*RouteMsg) error
	Recv() (*RouteMsg, error)
	grpc.ServerStream
}

type routeConnectGameAgentStreamServer struct {
	grpc.ServerStream
}

func (x *routeConnectGameAgentStreamServer) Send(m *RouteMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeConnectGameAgentStreamServer) Recv() (*RouteMsg, error) {
	m := new(RouteMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _RouteConnectGame_AgentRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteConnectGameServer).AgentRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.RouteConnectGame/AgentRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteConnectGameServer).AgentRegister(ctx, req.(*RegisterMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouteConnectGame_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.RouteConnectGame",
	HandlerType: (*RouteConnectGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AgentRegister",
			Handler:    _RouteConnectGame_AgentRegister_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentStream",
			Handler:       _RouteConnectGame_AgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connectToGame.proto",
}

func init() { proto.RegisterFile("connectToGame.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xbb, 0x2a, 0x25, 0x99, 0x34, 0x20, 0xa3, 0x68, 0x2c, 0x22, 0x61, 0x2f, 0xe6, 0x14,
	0x44, 0xaf, 0x82, 0x54, 0x11, 0xe9, 0x41, 0x28, 0xa3, 0x27, 0x6f, 0xeb, 0x66, 0x09, 0x05, 0x9b,
	0x0d, 0xd9, 0xc9, 0xc1, 0x57, 0xf1, 0x69, 0xa5, 0x6b, 0xc3, 0x5a, 0x28, 0xf4, 0x36, 0xf9, 0xb2,
	0x7c, 0xbf, 0xf9, 0x03, 0x27, 0xda, 0x36, 0x8d, 0xd1, 0xfc, 0x6e, 0x5f, 0xd4, 0xca, 0x94, 0x6d,
	0x67, 0xd9, 0x22, 0x6c, 0xe0, 0xac, 0x6d, 0xe5, 0x3d, 0x44, 0x64, 0x7b, 0x36, 0xaf, 0xae, 0xc6,
	0x4b, 0x88, 0x95, 0xd6, 0xb6, 0x6f, 0x78, 0x5e, 0x65, 0x22, 0x17, 0x45, 0x4c, 0x01, 0x20, 0xc2,
	0x51, 0xa5, 0x58, 0x65, 0x07, 0xb9, 0x28, 0x26, 0xe4, 0x6b, 0x69, 0x21, 0x21, 0x53, 0x2f, 0x1d,
	0x9b, 0x6e, 0xbf, 0x40, 0xc2, 0x24, 0x04, 0xcf, 0x2b, 0x2f, 0x8a, 0x69, 0x8b, 0xe1, 0x15, 0xc0,
	0xd2, 0x0d, 0xca, 0xec, 0x30, 0x17, 0x45, 0x44, 0xff, 0x88, 0xbc, 0x86, 0x74, 0xa8, 0xc9, 0xb4,
	0x5f, 0xdf, 0x78, 0x06, 0x63, 0xc7, 0x8a, 0x7b, 0xe7, 0xf3, 0x22, 0xda, 0x7c, 0xdd, 0xfe, 0x08,
	0x38, 0xf6, 0x83, 0x3d, 0xfd, 0xe9, 0xd7, 0xe3, 0xe3, 0x03, 0x24, 0xb3, 0xda, 0x34, 0xfc, 0xc6,
	0x9d, 0x51, 0x2b, 0x3c, 0x2d, 0x43, 0x76, 0x39, 0x6c, 0x61, 0xba, 0x93, 0xca, 0x51, 0x21, 0x6e,
	0x04, 0x3e, 0x43, 0xea, 0x05, 0x43, 0x0f, 0x78, 0xbe, 0xf5, 0x38, 0xac, 0x62, 0x7a, 0xb1, 0xeb,
	0x87, 0x6f, 0x59, 0x8e, 0x1e, 0xd3, 0x8f, 0xa4, 0xb6, 0x8e, 0x16, 0x7a, 0xb1, 0xbe, 0xc7, 0xe7,
	0xd8, 0x9f, 0xe5, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x78, 0xfb, 0x1f, 0xad, 0x01, 0x00,
	0x00,
}
