// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connectApp.proto

/*
Package gosRPcProto is a generated protocol buffer package.

It is generated from these files:
	connectApp.proto
	connectToGame.proto
	gameApp.proto

It has these top-level messages:
	DispatchRequest
	DispatchReply
	RouteMsg
	RegisterMsg
	RegisterReply
	DispatchGameRequest
	DispatchGameReply
*/
package gosRPcProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DispatchRequest struct {
	AccountId string `protobuf:"bytes,1,opt,name=accountId" json:"accountId,omitempty"`
	GroupId   string `protobuf:"bytes,2,opt,name=groupId" json:"groupId,omitempty"`
}

func (m *DispatchRequest) Reset()                    { *m = DispatchRequest{} }
func (m *DispatchRequest) String() string            { return proto.CompactTextString(m) }
func (*DispatchRequest) ProtoMessage()               {}
func (*DispatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DispatchRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *DispatchRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type DispatchReply struct {
	ConnectAppId   string `protobuf:"bytes,1,opt,name=connectAppId" json:"connectAppId,omitempty"`
	ConnectAppHost string `protobuf:"bytes,2,opt,name=connectAppHost" json:"connectAppHost,omitempty"`
	ConnectAppPort string `protobuf:"bytes,3,opt,name=connectAppPort" json:"connectAppPort,omitempty"`
}

func (m *DispatchReply) Reset()                    { *m = DispatchReply{} }
func (m *DispatchReply) String() string            { return proto.CompactTextString(m) }
func (*DispatchReply) ProtoMessage()               {}
func (*DispatchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DispatchReply) GetConnectAppId() string {
	if m != nil {
		return m.ConnectAppId
	}
	return ""
}

func (m *DispatchReply) GetConnectAppHost() string {
	if m != nil {
		return m.ConnectAppHost
	}
	return ""
}

func (m *DispatchReply) GetConnectAppPort() string {
	if m != nil {
		return m.ConnectAppPort
	}
	return ""
}

func init() {
	proto.RegisterType((*DispatchRequest)(nil), "connectApp.DispatchRequest")
	proto.RegisterType((*DispatchReply)(nil), "connectApp.DispatchReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Dispatcher service

type DispatcherClient interface {
	DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error)
}

type dispatcherClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherClient(cc *grpc.ClientConn) DispatcherClient {
	return &dispatcherClient{cc}
}

func (c *dispatcherClient) DispatchPlayer(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchReply, error) {
	out := new(DispatchReply)
	err := grpc.Invoke(ctx, "/connectApp.Dispatcher/DispatchPlayer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Dispatcher service

type DispatcherServer interface {
	DispatchPlayer(context.Context, *DispatchRequest) (*DispatchReply, error)
}

func RegisterDispatcherServer(s *grpc.Server, srv DispatcherServer) {
	s.RegisterService(&_Dispatcher_serviceDesc, srv)
}

func _Dispatcher_DispatchPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DispatcherServer).DispatchPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connectApp.Dispatcher/DispatchPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DispatcherServer).DispatchPlayer(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dispatcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connectApp.Dispatcher",
	HandlerType: (*DispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchPlayer",
			Handler:    _Dispatcher_DispatchPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "connectApp.proto",
}

func init() { proto.RegisterFile("connectApp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0x71, 0x2c, 0x28, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x79, 0x72, 0xf1, 0xbb, 0x64, 0x16, 0x17, 0x24, 0x96, 0x24, 0x67, 0x04, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x26, 0x26, 0x27, 0xe7, 0x97, 0xe6, 0x95, 0x78, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0x84, 0x24, 0xb8, 0xd8, 0xd3, 0x8b, 0xf2,
	0x4b, 0x0b, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0x72, 0x30, 0xae, 0x52, 0x33, 0x23, 0x17, 0x2f, 0xc2,
	0xac, 0x82, 0x9c, 0x4a, 0x21, 0x25, 0x2e, 0x1e, 0x84, 0x55, 0x70, 0xc3, 0x50, 0xc4, 0x84, 0xd4,
	0xb8, 0xf8, 0x10, 0x7c, 0x8f, 0xfc, 0xe2, 0x12, 0xa8, 0xb1, 0x68, 0xa2, 0xa8, 0xea, 0x02, 0xf2,
	0x8b, 0x4a, 0x24, 0x98, 0xd1, 0xd5, 0x81, 0x44, 0x8d, 0x22, 0xb8, 0xb8, 0x60, 0x8e, 0x48, 0x2d,
	0x12, 0xf2, 0xe2, 0xe2, 0x83, 0xf1, 0x02, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x84, 0xa4, 0xf5, 0x90,
	0xc2, 0x03, 0xcd, 0xeb, 0x52, 0x92, 0xd8, 0x25, 0x0b, 0x72, 0x2a, 0x95, 0x18, 0x9c, 0x78, 0xa3,
	0xb8, 0xd3, 0xf3, 0x8b, 0x83, 0x02, 0x92, 0x03, 0x40, 0xa1, 0x98, 0xc4, 0x06, 0x0e, 0x4c, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0xa8, 0x2b, 0x5e, 0x60, 0x01, 0x00, 0x00,
}
