// Generated by tools/gen_routes

package register

import (
	. "app/consts"
	"app/controllers"
	"gslib"
	"gslib/routes"
)

func Load() {
    routes.Add("EquipLoadParams", func(ctx interface{}, params interface{}) interface{} {
        instance := &controllers.EquipsController{Context: ctx.(*gslib.Player)}
        return instance.Load(params.(*EquipLoadParams))
    })
    routes.Add("EquipUnLoadParams", func(ctx interface{}, params interface{}) interface{} {
        instance := &controllers.EquipsController{Context: ctx.(*gslib.Player)}
        return instance.UnLoad(params.(*EquipUnLoadParams))
    })

}
